
module.exports = () => [
  {
    slug: 'loading-states',
    title: 'Loading spinner and dash',
    description: 'Basic loading state components to expand the vocabulary of Cloudscape.',
    image: 'assets/chasm.jpg',
    format: 'Documentation',
    topic: 'Components',
    discipline: 'Engineering',
    section: 'Details',
    vendor: 'Cloudscape',
    publicationDate: new Date('Jun 2, 2021'),
    tenets: [2, 3],
    referenceComponent: 'Spinner',
    referenceLink: 'https://cloudscape.design/components/spinner/'
  },
  {
    slug: 'icon-map',
    title: 'Icon map',
    description: 'Developer convenience component to aid in quickly finding the name of a particular icon.',
    image: 'assets/chasm.jpg',
    format: 'Documentation',
    topic: 'Components',
    discipline: 'Engineering',
    section: 'Helpers',
    vendor: 'Cloudscape',
    publicationDate: new Date('Jun 4, 2021'),
    tenets: [0],
    referenceComponent: 'Icon',
    referenceLink: 'https://cloudscape.design/components/icon/'
  },
  {
    slug: 'labeled-input',
    title: 'Labeled input',
    description: 'Labeled variation of the Input component that provides smart defaults.',
    image: 'assets/chasm.jpg',
    format: 'Documentation',
    topic: 'Components',
    discipline: 'Engineering',
    section: 'Forms',
    vendor: 'Cloudscape',
    publicationDate: new Date('Jun 17, 2021'),
    tenets: [0, 1, 3, 4],
    referenceComponent: 'Input',
    referenceLink: 'https://cloudscape.design/components/input/'
  },
  {
    slug: 'labeled-number',
    title: 'Labeled number',
    description: 'Labeled number display as seen in Cloudscape Dashboard demo.',
    image: 'assets/chasm.jpg',
    format: 'Documentation',
    topic: 'Components',
    discipline: 'Engineering',
    section: 'Details',
    vendor: 'Cloudscape',
    publicationDate: new Date('Jun 16, 2021'),
    tenets: [0, 1],
    referenceComponent: 'Dashboard',
    referenceLink: 'https://cloudscape.design/examples/react/dashboard.html'
  },
  {
    slug: 'spacing-constants',
    title: 'Spacing constants',
    description: 'Helper file for DRYing up the use of spacing objects in your project.',
    image: 'assets/chasm.jpg',
    format: 'Documentation',
    topic: 'Components',
    discipline: 'Engineering',
    section: 'Helpers',
    vendor: 'Cloudscape',
    publicationDate: new Date('Jun 3, 2021'),
    tenets: [0, 1, 2],
    referenceComponent: 'Dashboard',
    referenceLink: 'https://cloudscape.design/examples/react/dashboard.html'
  },
  {
    slug: 'generic-empty',
    title: 'Generic empty',
    description: 'Simple components designed to speed up creation of new Tables.',
    image: 'assets/chasm.jpg',
    format: 'Documentation',
    topic: 'Components',
    discipline: 'Engineering',
    section: 'Tables',
    vendor: 'Cloudscape',
    publicationDate: new Date('Jun 5, 2021'),
    tenets: [2, 3],
    referenceComponent: 'Dashboard',
    referenceLink: 'https://cloudscape.design/examples/react/dashboard.html'
  },
  {
    slug: 'bridging-the-chasm',
    title: 'Bridging the chasm: unifying design and development',
    description: 'Harmonious collaboration between design and development is crucial for crafting outstanding user experiences.',
    image: 'assets/chasm.jpg',
    format: 'Article',
    topic: 'Collaboration',
    discipline: 'Project management',
    section: 'Tools',
    vendor: 'Figma',
    publicationDate: new Date('Jun 1, 2021'),
  },
  // {
  //   slug: 'labeled-value',
  //   title: 'Labeled value',
  //   description: '',
  //   image: 'assets/chasm.jpg',
  //   format: 'Documentation',
  //   topic: 'Components',
  //   discipline: 'Engineering',
  //   section: 'Details',
  //   vendor: 'Cloudscape',
  //   publicationDate: new Date('Jun 5, 2021'),
  //   tenets: [1, 2],
  //   referenceComponent: 'Dashboard',
  //   referenceLink: 'https://cloudscape.design/examples/react/dashboard.html'
  // },
] .filter(item => {
  if (!item.publicationDate) return false;
  const today = new Date();
  if (today > item.publicationDate) return true;
  return false;
});