
module.exports = () => [
  {
    slug: 'loading-states',
    title: 'Loading spinner and dash',
    description: 'Basic loading state components to expand the vocabulary of Cloudscape.',
    image: 'assets/chasm.jpg',
    format: 'Documentation',
    topic: 'Components',
    discipline: 'Engineering',
    section: 'Details',
    vendor: 'Cloudscape',
    publicationDate: new Date('Jun 2, 2021'),
    tenets: [2, 3],
    referenceComponent: 'Spinner',
    referenceLink: 'https://cloudscape.design/components/spinner/'
  },
  {
    slug: 'icon-map',
    title: 'Icon map',
    description: 'Developer convenience component to aid in quickly finding the name of a particular icon.',
    image: 'assets/chasm.jpg',
    format: 'Documentation',
    topic: 'Components',
    discipline: 'Engineering',
    section: 'Helpers',
    vendor: 'Cloudscape',
    publicationDate: new Date('Jun 6, 2021'),
    tenets: [0],
    referenceComponent: 'Icon',
    referenceLink: 'https://cloudscape.design/components/icon/'
  },
  {
    slug: 'labeled-input',
    title: 'Labeled input',
    description: 'Labeled variation of the Input component that provides smart defaults.',
    image: 'assets/chasm.jpg',
    format: 'Documentation',
    topic: 'Components',
    discipline: 'Engineering',
    section: 'Forms',
    vendor: 'Cloudscape',
    publicationDate: new Date('Jun 19, 2021'),
    tenets: [0, 1, 3, 4],
    referenceComponent: 'Input',
    referenceLink: 'https://cloudscape.design/components/input/'
  },
  {
    slug: 'labeled-number',
    title: 'Labeled number',
    description: 'Labeled number display as seen in Cloudscape Dashboard demo.',
    image: 'assets/chasm.jpg',
    format: 'Documentation',
    topic: 'Components',
    discipline: 'Engineering',
    section: 'Details',
    vendor: 'Cloudscape',
    publicationDate: new Date('Jun 17, 2021'),
    tenets: [0, 1],
    referenceComponent: 'Dashboard',
    referenceLink: 'https://cloudscape.design/examples/react/dashboard.html'
  },
  {
    slug: 'spacing-constants',
    title: 'Spacing constants',
    description: 'Helper file for DRYing up the use of spacing objects in your project.',
    image: 'assets/chasm.jpg',
    format: 'Documentation',
    topic: 'Components',
    discipline: 'Engineering',
    section: 'Helpers',
    vendor: 'Cloudscape',
    publicationDate: new Date('Jun 4, 2021'),
    tenets: [0, 1, 2],
    referenceComponent: 'Dashboard',
    referenceLink: 'https://cloudscape.design/examples/react/dashboard.html'
  },
  {
    slug: 'generic-empty',
    title: 'Generic empty',
    description: 'Simple components designed to speed up creation of new Tables.',
    image: 'assets/chasm.jpg',
    format: 'Documentation',
    topic: 'Components',
    discipline: 'Engineering',
    section: 'Tables',
    vendor: 'Cloudscape',
    publicationDate: new Date('Jun 8, 2021'),
    tenets: [2, 3],
    referenceComponent: 'Dashboard',
    referenceLink: 'https://cloudscape.design/examples/react/dashboard.html'
  },
  {
    slug: 'labeled-value',
    title: 'Labeled value',
    description: 'A simple, generic component for a common Details page pattern.',
    image: 'assets/chasm.jpg',
    format: 'Documentation',
    topic: 'Components',
    discipline: 'Engineering',
    section: 'Details',
    vendor: 'Cloudscape',
    publicationDate: new Date('Jun 10, 2021'),
    tenets: [1, 2],
    referenceComponent: 'Dashboard',
    referenceLink: 'https://cloudscape.design/examples/react/dashboard.html'
  },
  {
    slug: 'unsaved-changes-modal',
    title: 'Unsaved changes modal',
    description: 'The modal described in the documentation for Cloudscape\'s Wizard Component.',
    image: 'assets/chasm.jpg',
    format: 'Documentation',
    topic: 'Components',
    discipline: 'Engineering',
    section: 'Forms',
    vendor: 'Cloudscape',
    publicationDate: new Date('Jun 12, 2021'),
    tenets: [0, 2],
    referenceComponent: 'Wizard',
    referenceLink: 'https://cloudscape.design/components/wizard/'
  },
  {
    slug: 'bridging-the-chasm',
    title: 'How can design and development collaborate better?',
    description: 'Harmonious collaboration between design and development is crucial for crafting outstanding user experiences.',
    image: 'assets/chasm.jpg',
    format: 'Article',
    topic: 'Collaboration',
    discipline: 'Project management',
    section: 'Tools',
    vendor: 'Figma',
    publicationDate: new Date('Jun 1, 2021'),
  },
  {
    slug: 'anatomy-of-a-design-system',
    title: 'What are the parts of a design system?',
    description: 'A design system consists of several key elements that work together to provide a cohesive and standardized approach to digital design.',
    image: 'assets/chasm.jpg',
    format: 'Article',
    topic: 'Design Systems',
    discipline: 'Design',
    section: 'Foundation',
    author: 'Chad Lumley & Bishop Zareh',
    publicationDate: new Date('Jun 3, 2021'),
  },
  {
    slug: 'documenting-a-design-system',
    title: 'How should I document my design system?',
    description: 'Document your design system with assets, process and documentation.',
    image: 'assets/chasm.jpg',
    format: 'Article',
    topic: 'Design Systems',
    discipline: 'Writing',
    section: 'Delivery',
    author: 'Chad Lumley & Bishop Zareh',
    publicationDate: new Date('Jun 5, 2021'),
  },
  {
    slug: 'design-system-lifecycle',
    title: 'What is the lifecycle of a design system?',
    description: 'Explores the stages of a design system\'s maturity.',
    image: 'assets/chasm.jpg',
    format: 'Article',
    topic: 'Design Systems',
    discipline: 'Design',
    section: 'Delivery',
    author: 'Chad Lumley & Bishop Zareh',
    publicationDate: new Date('Jun 7, 2021'),
  },
] .filter(item => {
  if (!item.publicationDate) return false;
  const today = new Date();
  if (today > item.publicationDate) return true;
  return false;
});