
export const redirects = [
  ['/upload', '/'],
  ['/biography', '/'],
  ['/resume', '/'],
  ['/contact', '/'],
  ['/exhibitions', '/'],
  ['/fantasy-data-viz-2017', '/'],
  ['/colorado-webcams', '/'],
  ['/karsh-hagan-first-on-site', '/'],
  ['/venice-tx-homeostasis-lab', '/'],
  ['/harvard-book-store-interactive-interface', '/'],
  ['/squadron-app-prototype', '/'],
  ['/aspen-give-a-flake', '/'],
  ['/karsh-hagan-undercanvas', '/'],
  ['/rbg-x-hsl', 'https://vimeo.com/211040647'],
  ['/fourth-screen-screen-readers-frontend', '/'],
  ['/do-i-need-a-design-system', '/'],

  ['/articles/type-helpers', '/articles/cloudscape-type-helpers'],
  ['/at-and-t-digital-life-web-3d', '/articles/att-digital-life-web-3d'],
  ['/using-nfts-to-protect-creative-works', '/articles/using-nfts-to-protect-creative-works'],
  ['/american-analog-set-res-fest', '/articles/american-analog-set-res-fest'],
  ['/karsh-hagan-office-pet', '/articles/karsh-hagan-office-pet'],
  ['/articles/diamond-age-waitlist', '/articles/love-street-public-beta'],
  ['/articles/love-street-public-beta', '/articles/love-street-app'],
];
